services:
  # Service with auth and workspace mounts for OpenCode
  opencode-auth-workspace:
    build:
      context: ${CONTEXT}
      dockerfile: ${OPENCODE_CONTAINER_DIR}/Dockerfile
    stdin_open: true
    tty: true
    userns_mode: keep-id
    # profiles:
    #   - auth-workspace
    volumes:
      - ${OPENCODE_CONFIG_DIR:-~}/.config/opencode:/home/node/.config/opencode
      - ${OPENCODE_CONFIG_DIR:-~}/.opencode:/home/node/.local/share/opencode
      # - ${CONTEXT}:/workspace
    working_dir: /workspace
